//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.19 at 03:39:11 PM EDT 
//


package edu.harvard.i2b2.ncboclient.datavo.ncbo.all;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="classType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" type="{}propertiesType"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="synonymCollection" type="{}synonymCollectionType"/>
 *         &lt;element name="childrenCollection" type="{}childrenCollectionType"/>
 *         &lt;element name="linksCollection" type="{}linksCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "classType", propOrder = {
    "properties",
    "id",
    "type",
    "synonymCollection",
    "childrenCollection",
    "linksCollection"
})
public class ClassType {

    @XmlElement(required = true)
    protected PropertiesType properties;
    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected SynonymCollectionType synonymCollection;
    @XmlElement(required = true)
    protected ChildrenCollectionType childrenCollection;
    @XmlElement(required = true)
    protected LinksCollectionType linksCollection;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the synonymCollection property.
     * 
     * @return
     *     possible object is
     *     {@link SynonymCollectionType }
     *     
     */
    public SynonymCollectionType getSynonymCollection() {
        return synonymCollection;
    }

    /**
     * Sets the value of the synonymCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SynonymCollectionType }
     *     
     */
    public void setSynonymCollection(SynonymCollectionType value) {
        this.synonymCollection = value;
    }

    /**
     * Gets the value of the childrenCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ChildrenCollectionType }
     *     
     */
    public ChildrenCollectionType getChildrenCollection() {
        return childrenCollection;
    }

    /**
     * Sets the value of the childrenCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildrenCollectionType }
     *     
     */
    public void setChildrenCollection(ChildrenCollectionType value) {
        this.childrenCollection = value;
    }

    /**
     * Gets the value of the linksCollection property.
     * 
     * @return
     *     possible object is
     *     {@link LinksCollectionType }
     *     
     */
    public LinksCollectionType getLinksCollection() {
        return linksCollection;
    }

    /**
     * Sets the value of the linksCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinksCollectionType }
     *     
     */
    public void setLinksCollection(LinksCollectionType value) {
        this.linksCollection = value;
    }

}
