//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.19 at 03:39:11 PM EDT 
//


package edu.harvard.i2b2.ncboclient.datavo.ncbo.all;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.harvard.i2b2.ncboclient.datavo.ncbo.all package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Class_QNAME = new QName("", "class");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.harvard.i2b2.ncboclient.datavo.ncbo.all
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChildrenCollectionType }
     * 
     */
    public ChildrenCollectionType createChildrenCollectionType() {
        return new ChildrenCollectionType();
    }

    /**
     * Create an instance of {@link LinksCollectionType }
     * 
     */
    public LinksCollectionType createLinksCollectionType() {
        return new LinksCollectionType();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link SubClassOfCollectionType }
     * 
     */
    public SubClassOfCollectionType createSubClassOfCollectionType() {
        return new SubClassOfCollectionType();
    }

    /**
     * Create an instance of {@link LinksType }
     * 
     */
    public LinksType createLinksType() {
        return new LinksType();
    }

    /**
     * Create an instance of {@link PageLinksType }
     * 
     */
    public PageLinksType createPageLinksType() {
        return new PageLinksType();
    }

    /**
     * Create an instance of {@link AllTermsType }
     * 
     */
    public AllTermsType createAllTermsType() {
        return new AllTermsType();
    }

    /**
     * Create an instance of {@link NotationCollectionType }
     * 
     */
    public NotationCollectionType createNotationCollectionType() {
        return new NotationCollectionType();
    }

    /**
     * Create an instance of {@link CuiCollectionType }
     * 
     */
    public CuiCollectionType createCuiCollectionType() {
        return new CuiCollectionType();
    }

    /**
     * Create an instance of {@link CollectionType }
     * 
     */
    public CollectionType createCollectionType() {
        return new CollectionType();
    }

    /**
     * Create an instance of {@link SynonymCollectionType }
     * 
     */
    public SynonymCollectionType createSynonymCollectionType() {
        return new SynonymCollectionType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link TypeCollectionType }
     * 
     */
    public TypeCollectionType createTypeCollectionType() {
        return new TypeCollectionType();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link ChildrenType }
     * 
     */
    public ChildrenType createChildrenType() {
        return new ChildrenType();
    }

    /**
     * Create an instance of {@link HasSTYCollectionType }
     * 
     */
    public HasSTYCollectionType createHasSTYCollectionType() {
        return new HasSTYCollectionType();
    }

    /**
     * Create an instance of {@link TuiCollectionType }
     * 
     */
    public TuiCollectionType createTuiCollectionType() {
        return new TuiCollectionType();
    }

    /**
     * Create an instance of {@link PrefLabelCollectionType }
     * 
     */
    public PrefLabelCollectionType createPrefLabelCollectionType() {
        return new PrefLabelCollectionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllTermsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "class")
    public JAXBElement<AllTermsType> createClass(AllTermsType value) {
        return new JAXBElement<AllTermsType>(_Class_QNAME, AllTermsType.class, null, value);
    }

}
