//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.19 at 03:39:11 PM EDT 
//


package edu.harvard.i2b2.ncboclient.datavo.ncbo.all;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prefLabelCollection" type="{}prefLabelCollectionType"/>
 *         &lt;element name="tuiCollection" type="{}tuiCollectionType"/>
 *         &lt;element name="cuiCollection" type="{}cuiCollectionType"/>
 *         &lt;element name="notationCollection" type="{}notationCollectionType"/>
 *         &lt;element name="subClassOfCollection" type="{}subClassOfCollectionType"/>
 *         &lt;element name="typeCollection" type="{}typeCollectionType"/>
 *         &lt;element name="hasSTYCollection" type="{}hasSTYCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertiesType", propOrder = {
    "prefLabelCollection",
    "tuiCollection",
    "cuiCollection",
    "notationCollection",
    "subClassOfCollection",
    "typeCollection",
    "hasSTYCollection"
})
public class PropertiesType {

    @XmlElement(required = true)
    protected PrefLabelCollectionType prefLabelCollection;
    @XmlElement(required = true)
    protected TuiCollectionType tuiCollection;
    @XmlElement(required = true)
    protected CuiCollectionType cuiCollection;
    @XmlElement(required = true)
    protected NotationCollectionType notationCollection;
    @XmlElement(required = true)
    protected SubClassOfCollectionType subClassOfCollection;
    @XmlElement(required = true)
    protected TypeCollectionType typeCollection;
    @XmlElement(required = true)
    protected HasSTYCollectionType hasSTYCollection;

    /**
     * Gets the value of the prefLabelCollection property.
     * 
     * @return
     *     possible object is
     *     {@link PrefLabelCollectionType }
     *     
     */
    public PrefLabelCollectionType getPrefLabelCollection() {
        return prefLabelCollection;
    }

    /**
     * Sets the value of the prefLabelCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrefLabelCollectionType }
     *     
     */
    public void setPrefLabelCollection(PrefLabelCollectionType value) {
        this.prefLabelCollection = value;
    }

    /**
     * Gets the value of the tuiCollection property.
     * 
     * @return
     *     possible object is
     *     {@link TuiCollectionType }
     *     
     */
    public TuiCollectionType getTuiCollection() {
        return tuiCollection;
    }

    /**
     * Sets the value of the tuiCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TuiCollectionType }
     *     
     */
    public void setTuiCollection(TuiCollectionType value) {
        this.tuiCollection = value;
    }

    /**
     * Gets the value of the cuiCollection property.
     * 
     * @return
     *     possible object is
     *     {@link CuiCollectionType }
     *     
     */
    public CuiCollectionType getCuiCollection() {
        return cuiCollection;
    }

    /**
     * Sets the value of the cuiCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CuiCollectionType }
     *     
     */
    public void setCuiCollection(CuiCollectionType value) {
        this.cuiCollection = value;
    }

    /**
     * Gets the value of the notationCollection property.
     * 
     * @return
     *     possible object is
     *     {@link NotationCollectionType }
     *     
     */
    public NotationCollectionType getNotationCollection() {
        return notationCollection;
    }

    /**
     * Sets the value of the notationCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotationCollectionType }
     *     
     */
    public void setNotationCollection(NotationCollectionType value) {
        this.notationCollection = value;
    }

    /**
     * Gets the value of the subClassOfCollection property.
     * 
     * @return
     *     possible object is
     *     {@link SubClassOfCollectionType }
     *     
     */
    public SubClassOfCollectionType getSubClassOfCollection() {
        return subClassOfCollection;
    }

    /**
     * Sets the value of the subClassOfCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubClassOfCollectionType }
     *     
     */
    public void setSubClassOfCollection(SubClassOfCollectionType value) {
        this.subClassOfCollection = value;
    }

    /**
     * Gets the value of the typeCollection property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCollectionType }
     *     
     */
    public TypeCollectionType getTypeCollection() {
        return typeCollection;
    }

    /**
     * Sets the value of the typeCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCollectionType }
     *     
     */
    public void setTypeCollection(TypeCollectionType value) {
        this.typeCollection = value;
    }

    /**
     * Gets the value of the hasSTYCollection property.
     * 
     * @return
     *     possible object is
     *     {@link HasSTYCollectionType }
     *     
     */
    public HasSTYCollectionType getHasSTYCollection() {
        return hasSTYCollection;
    }

    /**
     * Sets the value of the hasSTYCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link HasSTYCollectionType }
     *     
     */
    public void setHasSTYCollection(HasSTYCollectionType value) {
        this.hasSTYCollection = value;
    }

}
