//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.19 at 03:39:11 PM EDT 
//


package edu.harvard.i2b2.ontclient.datavo.vdo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.harvard.i2b2.ontclient.datavo.vdo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OntologyProcessStatus_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "ontology_process_status");
    private final static QName _OntologyProcessStatusList_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "ontology_process_status_list");
    private final static QName _Concepts_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "concepts");
    private final static QName _DirtyState_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "dirty_state");
    private final static QName _AddChild_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "add_child");
    private final static QName _Modifiers_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "modifiers");
    private final static QName _ModifyChild_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "modify_child");
    private final static QName _AddModifier_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "add_modifier");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.harvard.i2b2.ontclient.datavo.vdo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModifyChildType }
     * 
     */
    public ModifyChildType createModifyChildType() {
        return new ModifyChildType();
    }

    /**
     * Create an instance of {@link ConceptsType }
     * 
     */
    public ConceptsType createConceptsType() {
        return new ConceptsType();
    }

    /**
     * Create an instance of {@link OntologyProcessStatusListType }
     * 
     */
    public OntologyProcessStatusListType createOntologyProcessStatusListType() {
        return new OntologyProcessStatusListType();
    }

    /**
     * Create an instance of {@link OntologyProcessStatusType }
     * 
     */
    public OntologyProcessStatusType createOntologyProcessStatusType() {
        return new OntologyProcessStatusType();
    }

    /**
     * Create an instance of {@link ModifierType }
     * 
     */
    public ModifierType createModifierType() {
        return new ModifierType();
    }

    /**
     * Create an instance of {@link ConceptType }
     * 
     */
    public ConceptType createConceptType() {
        return new ConceptType();
    }

    /**
     * Create an instance of {@link ModifiersType }
     * 
     */
    public ModifiersType createModifiersType() {
        return new ModifiersType();
    }

    /**
     * Create an instance of {@link XmlValueType }
     * 
     */
    public XmlValueType createXmlValueType() {
        return new XmlValueType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OntologyProcessStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "ontology_process_status")
    public JAXBElement<OntologyProcessStatusType> createOntologyProcessStatus(OntologyProcessStatusType value) {
        return new JAXBElement<OntologyProcessStatusType>(_OntologyProcessStatus_QNAME, OntologyProcessStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OntologyProcessStatusListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "ontology_process_status_list")
    public JAXBElement<OntologyProcessStatusListType> createOntologyProcessStatusList(OntologyProcessStatusListType value) {
        return new JAXBElement<OntologyProcessStatusListType>(_OntologyProcessStatusList_QNAME, OntologyProcessStatusListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConceptsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "concepts")
    public JAXBElement<ConceptsType> createConcepts(ConceptsType value) {
        return new JAXBElement<ConceptsType>(_Concepts_QNAME, ConceptsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DirtyValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "dirty_state")
    public JAXBElement<DirtyValueType> createDirtyState(DirtyValueType value) {
        return new JAXBElement<DirtyValueType>(_DirtyState_QNAME, DirtyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConceptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "add_child")
    public JAXBElement<ConceptType> createAddChild(ConceptType value) {
        return new JAXBElement<ConceptType>(_AddChild_QNAME, ConceptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifiersType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "modifiers")
    public JAXBElement<ModifiersType> createModifiers(ModifiersType value) {
        return new JAXBElement<ModifiersType>(_Modifiers_QNAME, ModifiersType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifyChildType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "modify_child")
    public JAXBElement<ModifyChildType> createModifyChild(ModifyChildType value) {
        return new JAXBElement<ModifyChildType>(_ModifyChild_QNAME, ModifyChildType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "add_modifier")
    public JAXBElement<ModifierType> createAddModifier(ModifierType value) {
        return new JAXBElement<ModifierType>(_AddModifier_QNAME, ModifierType.class, null, value);
    }

}
